language: English
sudo: required
servides:
    - docker

before_install:
    - docker build -t htakuya614/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true htakuya614/docker-react npm run test
