language: English
sudo: required
servides:
    - docker

before_install:
    - docker build -t htakuya614/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true htakuya614/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "dpcker-react"
    env: "DpckerReact-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-363888725171"
    bucket_path: "dpcker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY